Integrated form submission functionality
haifa-dev/official-website pull request #42
Opened 2020-10-08 20:11 UTC by Polarts

2020-10-08 20:24 UTC, Tomer51m commented on src/components/ProjectRequestForm/FormConfirmation.jsx
> +          ? <LoadingDots/>
Please change the color of the dot from black to the website green.

2020-10-08 20:38 UTC, Tomer51m requested changes

2020-10-08 20:38 UTC, Tomer51m commented on src/components/ProjectRequestForm/FormConfirmation.jsx
> +          ? <LoadingDots/>
Please change the dots color from black to the website's green.

2020-10-08 20:38 UTC, Tomer51m commented on src/services/requestForm.service.js
> +            headers:{
The convention is that headers should be before the body. Make the code more readable.

2020-10-08 20:38 UTC, Tomer51m commented on src/services/requestForm.service.js
> +    if (errorMsg.startsWith('"')) {
Not very robust. Would be better to match expected response from server.
Also, you forgot to handle 'internal server error' message that the server can respond with.

2020-10-09 11:52 UTC, Polarts commented
@Tomer51m I addressed your comments, and also added a feature to mark the error row in the table with alert-danger. Please take a look

2020-10-11 14:14 UTC, Tomer51m approved these changes

2020-10-11 14:15 UTC, merged